#!/bin/bash

# This hook is called with the snake-cased name of the theme that has just been set.
# To put it into use, remove .sample from the name.

# Example: Show the name of the theme that was just set.
# notify-send "New theme" "Your new theme is $1"

# Make sure to update the mako config with my updates
# after theme change destroys it
cat "$HOME/.config/mako/my_config" >>"$HOME/.config/mako/config"
