#!/bin/env bash

# Checks if an ip field is present, then checks status of connection
# 1 for on, 0 for off, -1 for error
CONNECTED=$(jq -e '
  if (.details.location | .ipv4 // .ipv6) then 
    if .state == "connected" then 1
    elif .state == "disconnected" then 0
    else -1 end
  else -1 end
  ' 2>/dev/null <<<"$(mullvad status -j)") || CONNECTED=-1

if (("$CONNECTED" == 1)); then
  mullvad disconnect

else
  mullvad connect

fi
