#!/bin/env bash

exists() {
  command -v "$1" &>/dev/null
}

create-url() {
  if [[ "$#" -ne 2 ]]; then
    echo "Usage: create-url <url-name> <url>"
  else
    printf "<meta http-equiv=\"refresh\" content=\"0; url=%s\"/>" "$2" >"./$1.html"
  fi
}

ls_apps() {
  pacman -Qetq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'
}

open() {
  for file in "$@"; do
    xdg-open "$file" >/dev/null 2>&1 &
    disown $!
  done
}

# Write iso file to sd card
iso2sd() {
  if (($# < 1)); then
    echo "Usage: iso2sd <input_file> [output_device]"
    echo "Example: iso2sd ~/Downloads/ubuntu-25.04-desktop-amd64.iso /dev/sda"
    return 1
  fi

  local iso="$1"
  local drive="$2"

  if [[ -z $drive ]]; then
    local available_sds
    available_sds=$(lsblk -dpno NAME -l /dev/sd?)

    if [[ -z $available_sds ]]; then
      echo "No SD drives found and no drive specified"
      return 1
    fi

    drive=$(omarchy-drive-select "$available_sds")

    if [[ -z $drive ]]; then
      echo "No drive selected"
      return 1
    fi
  fi

  sudo dd bs=4M status=progress oflag=sync if="$iso" of="$drive"
  sudo eject "$drive"
}
