# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = omarchy-launch-or-focus signal "uwsm-app -- signal-desktop"
exec-once = uwsm app -- hyprsunset
exec-once = "$HOME/.config/hypr/scripts/setup_network"

exec-once = [workspace 1 ] $browser
exec-once = [workspace 2 silent] uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c 'tmux new -A -s $("$HOME/.config/hypr/scripts/cap_term_name")'
