# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = omarchy-launch-or-focus signal "uwsm-app -- signal-desktop"
exec-once = uwsm app -- hyprsunset

exec-once = [workspace 1 ] $browser
exec-once = [workspace 2 silent ] kitty -- bash -c "$HOME/.config/hypr/scripts/fastfetch_wait && clear && fastfetch; exec bash"
exec-once = [workspace 3 silent ] omarchy-launch-or-focus vesktop "uwsm-app -- vesktop"

exec-once = $HOME/.config/hypr/scripts/setup_home.sh
